# The URL the site will be built for
base_url = "/"

title = "Belen Design"
description = "A single page theme for a professional online presense."

# Whether to generate a RSS feed automatically
generate_feed = false
feed_filename = "rss.xml"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# Built in taxonomies of zplit.
taxonomies = [
#           {name = "tags"},
#           {name = "categories"},
]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]

author = "Belen Link"

[extra.content]

intro_tagline = "Designer. Stylist. Nomad."

[extra.visual]

background = "images/background.jpg"

[extra.lists]

connect = [
    { url = "/blog", text="Blog", new_tab = true },
    { url = "#", text="Email", new_tab = false },
    { url = "#", text="Newsletter", new_tab = false },
]

social = [
    {url = "https://t.me/zwitterio", text = "Telegram"},
    {url = "https://twitter.com/gicrisf", text = "Twitter"},
    {url = "https://github.com/gicrisf", text = "Github"},
]

# network = []
